/**
 * PF2E bestiary types.
 *
 * The dataset is generated by `scripts/fetch-pf2e-data.mjs` into
 * `src/data/pf2e/bestiary.json` and holds only the mechanical fields an
 * encounter builder needs, plus source/page for attribution. Because the data
 * lives in its own file it can be regenerated without touching app code.
 */

export interface Creature {
  name: string;
  /** PF2E creature level (-1 … 25). */
  level: number;
  size: string;
  rarity: string;
  /** PF2E creature-type traits, e.g. ["undead"], ["humanoid"]. */
  types: string[];
  /** Remaining descriptive traits, e.g. ["fire", "mindless"]. */
  traits: string[];
  /** Source book abbreviation, e.g. "B1". */
  source: string;
  page?: number;
}

export interface BestiaryMeta {
  generatedAt: string;
  source: string;
  note: string;
  sources: Record<string, string>;
}

export interface BestiaryData {
  meta: BestiaryMeta;
  creatures: Creature[];
}

export interface CreatureFilters {
  /** Free-text match against the creature name. */
  search?: string;
  /** Creature types to include (OR). Empty/undefined = any. */
  types?: string[];
  /** Rarities to include. Empty/undefined = any. */
  rarities?: string[];
  /** Sizes to include. Empty/undefined = any. */
  sizes?: string[];
  /** Source books to include. Empty/undefined = any. */
  sources?: string[];
  minLevel?: number;
  maxLevel?: number;
}
